FROM maven:3.9-eclipse-temurin-21 AS build

WORKDIR /workspace

COPY expense-app-managers/pom.xml .
COPY expense-app-managers/src ./src

RUN mvn clean package -DskipTests


FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=build /workspace/target/expense-app-managers-1.0-SNAPSHOT.jar app.jar

COPY expense-app-managers/src/test/resources/testDatabase.db /app/testDatabase.db

EXPOSE 5001

ENTRYPOINT ["java", "-jar", "app.jar", "/app/testDatabase.db"]