FROM python:3.12-slim

WORKDIR /app

COPY python/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY python ./python
COPY expense-app-managers/src/test/resources/testDatabase.db /app/testDatabase.db

RUN mkdir -p /var/lib/expense-data

EXPOSE 5000

ENV EXPENSE_DB_PATH=/var/lib/expense-data/testDatabase.db

CMD ["/bin/sh", "-c", "\
if [ ! -f /var/lib/expense-data/testDatabase.db ]; then \
    cp /app/testDatabase.db /var/lib/expense-data/testDatabase.db; \
fi && \
python python/api/app.py \
"]