FROM python:3.12-slim

WORKDIR /app

COPY python/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install behave selenium

COPY python/api ./api

WORKDIR /app/api/features

CMD ["behave"]